/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1B.glb -o 1B.tsx 
Refactored to support PBR texture overrides and modular openings
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import type { PBRTextureSet } from '@/hooks/usePBRTextures'
import type { ExteriorConfig } from '@/types/configurator'
import { ComponentProps } from 'react'
import { SmartMesh } from '../../SmartMesh'
import { OpeningSlot } from './OpeningSlot'
import { MODEL_1B_OPENINGS } from './1B.config'

type GLTFResult = GLTF & {
    nodes: {
        Awning_DoorEnt_Front_1B: THREE.Mesh
        Black_Roof_1B: THREE.Mesh
        Bottom_1B: THREE.Mesh
        Deck_1B: THREE.Mesh
        DoorEnt_1B: THREE.Mesh
        ElectricalPanel1_Conduit_1B: THREE.Mesh
        Exhaust_1B: THREE.Mesh
        Frame_Around_1B: THREE.Mesh
        Frame_Around_W_1B: THREE.Mesh
        Frame_DW_1B: THREE.Mesh
        Frame_DW_channel_1B: THREE.Mesh
        Frame_DW_W_1B: THREE.Mesh
        Glass_1B: THREE.Mesh
        GlassDoor_1B: THREE.Mesh
        Piles_1B: THREE.Mesh
        Roof_1B: THREE.Mesh
        Sanr_1B: THREE.Mesh
        Spigot_1B: THREE.Mesh
        Undersructure_1B: THREE.Mesh
        Wall_e_1B: THREE.Mesh
        Window_1B: THREE.Mesh
        Frame_FrontWindow_1B: THREE.Mesh
        Frame_FrontWindow__channel_1B: THREE.Mesh
        Frame_FrontWindow_W_1B: THREE.Mesh
        Frame_m_FrontWindow_1B: THREE.Mesh
        Glass_Front_1B: THREE.Mesh
        Socket_e_Front_1B: THREE.Mesh
        Wall_e_FrontWindow_1B: THREE.Mesh
        Frame_e_LefttWindow_1B: THREE.Mesh
        Frame_e_LefttWindow_W_1B: THREE.Mesh
        Frame_m_LefttWindow_1B: THREE.Mesh
        Glass_e_LefttWindow_1B: THREE.Mesh
        Socket_e_Left_1B: THREE.Mesh
        Wall_e_LefttWindow_1B: THREE.Mesh
        Awning_Front_1B: THREE.Mesh
        Deck_Front_1B: THREE.Mesh
        Door_Front_1B: THREE.Mesh
        Door_GlassFront_1B: THREE.Mesh
        Downlight_e_Front_1B: THREE.Mesh
        Frame_m_FrontDoor_1B: THREE.Mesh
        Frame_m_FrontDoor__channel_1B: THREE.Mesh
        Frame_m_FrontDoor_W_1B: THREE.Mesh
        Socket_e_DDF_1B: THREE.Mesh
        Undersructure_Front_1B: THREE.Mesh
        Wall_e_FrontDoor_1B: THREE.Mesh
        Awning_Left_1B: THREE.Mesh
        Deck_Left_1B: THREE.Mesh
        Door_GlassLeft_1B: THREE.Mesh
        Door_Left_1B: THREE.Mesh
        Downlight_e_Left_1B: THREE.Mesh
        Frame_LeftDoor_1B: THREE.Mesh
        Frame_LeftDoor_W_1B: THREE.Mesh
        Undersructure_Left_1B: THREE.Mesh
        Wall_e_LeftDoor_1B: THREE.Mesh
        ConstSP_Left_1B: THREE.Mesh
        Shield_Left_1B: THREE.Mesh
        SP_Left_1B_1: THREE.Mesh
        SP_Left_1B_2: THREE.Mesh
        ConstSP_Right_1B: THREE.Mesh
        Shield_Right_1B: THREE.Mesh
        SP_Right_1B_1: THREE.Mesh
        SP_Right_1B_2: THREE.Mesh
        ElectricalPanel_Conduit_1B: THREE.Mesh
        Tesla_powerwall_1: THREE.Mesh
        Tesla_powerwall_2: THREE.Mesh
        Tesla_shadow_1: THREE.Mesh
        Tesla_shadow_2: THREE.Mesh
    }
    materials: {
        Color_Exterior: THREE.MeshStandardMaterial
        Black: THREE.MeshStandardMaterial
        Color_Dark: THREE.MeshStandardMaterial
        Cedar: THREE.MeshStandardMaterial
        Dark_Bronze: THREE.MeshStandardMaterial
        Metal_details: THREE.MeshStandardMaterial
        Frame_Around: THREE.MeshStandardMaterial
        Color_Exterior_channels: THREE.MeshStandardMaterial
        Color_Exterior_Wood: THREE.MeshStandardMaterial
        glassClear: THREE.MeshPhysicalMaterial
        glassDoor: THREE.MeshPhysicalMaterial
        Color_Piles: THREE.MeshStandardMaterial
        Color_Roof: THREE.MeshStandardMaterial
        Bronze: THREE.MeshStandardMaterial
        Color_ExteriorSupp: THREE.MeshStandardMaterial
        Color_Exterior_walls: THREE.MeshStandardMaterial
        Color_Solar: THREE.MeshStandardMaterial
        Solar_Panel: THREE.MeshStandardMaterial
        Tesla: THREE.MeshStandardMaterial
        Tesla_box: THREE.MeshStandardMaterial
        Tesla_wall: THREE.MeshStandardMaterial
        Tesla_floor: THREE.MeshStandardMaterial
    }
}

interface ModelProps extends ComponentProps<'group'> {
    textures?: {
        roof?: PBRTextureSet | null
        siding?: PBRTextureSet | null
    }
    exterior?: ExteriorConfig
}

/**
 * ModelExterior Component
 * Groups and renders all exterior elements (walls, roof, frames)
 * Preserves transform hierarchy by keeping meshes in their original positions
 */
function ModelExterior({
    nodes,
    materials,
    textures,
    exterior,
}: {
    nodes: GLTFResult['nodes']
    materials: GLTFResult['materials']
    textures?: {
        roof?: PBRTextureSet | null
        siding?: PBRTextureSet | null
    }
    exterior?: ExteriorConfig
}) {
    // Use textures directly - they're already determined in ConfigurableModel
    // based on the material type (wood/concrete for siding, tiles for roof)
    const sidingTexture = textures?.siding || null
    const roofTexture = textures?.roof || null

    return (
        <group>
            {/* Exterior Walls - All Wall_e_* nodes with preserved transforms */}
            <SmartMesh
                geometry={nodes.Wall_e_1B.geometry}
                defaultMaterial={materials.Color_Exterior_walls}
                textureSet={sidingTexture}
                color={exterior?.siding.color}
                position={[-2.431, -0.106, -2.254]}
                rotation={[0, -1.571, 0]}
                scale={0.025}
            />
            <SmartMesh
                geometry={nodes.Wall_e_FrontWindow_1B.geometry}
                defaultMaterial={materials.Color_Exterior_walls}
                textureSet={sidingTexture}
                color={exterior?.siding.color}
                position={[-5.072, -0.161, -0.196]}
                rotation={[0, -1.571, 0]}
                scale={0.025}
            />
            <SmartMesh
                geometry={nodes.Wall_e_LefttWindow_1B.geometry}
                defaultMaterial={materials.Color_Exterior_walls}
                textureSet={sidingTexture}
                color={exterior?.siding.color}
                rotation={[0, 1.571, 0]}
                scale={0.025}
            />
            <SmartMesh
                geometry={nodes.Wall_e_FrontDoor_1B.geometry}
                defaultMaterial={materials.Color_Exterior_walls}
                textureSet={sidingTexture}
                color={exterior?.siding.color}
                position={[-5.072, -0.161, -0.196]}
                rotation={[0, -1.571, 0]}
                scale={0.025}
            />
            <SmartMesh
                geometry={nodes.Wall_e_LeftDoor_1B.geometry}
                defaultMaterial={materials.Color_Exterior_walls}
                textureSet={sidingTexture}
                color={exterior?.siding.color}
                position={[0.197, 0.405, 0.182]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={0.025}
            />

            {/* Roof - Roof_1B and Sanr_1B */}
            <SmartMesh
                geometry={nodes.Roof_1B.geometry}
                defaultMaterial={materials.Color_Roof}
                textureSet={roofTexture}
                color={exterior?.roof.color}
                position={[0, 2.099, 0]}
                scale={0.025}
            />
            <SmartMesh
                geometry={nodes.Sanr_1B.geometry}
                defaultMaterial={materials.Color_Roof}
                textureSet={roofTexture}
                color={exterior?.roof.color}
                position={[-0.148, 2.367, 0.289]}
                rotation={[0.394, 0.175, 0]}
                scale={0.025}
            />

            {/* Frames - Root level frames (not part of openings) */}
            <mesh geometry={nodes.Frame_Around_1B.geometry} position={[1.516, -1.473, 0]} scale={0.025}>
                <meshStandardMaterial color={exterior?.frames.color || '#4a3728'} />
            </mesh>
            <mesh geometry={nodes.Frame_Around_W_1B.geometry} material={materials.Frame_Around} position={[1.516, -1.473, 0]} scale={0.025} />
            <mesh geometry={nodes.Frame_DW_1B.geometry} position={[-1.829, 0.336, 2.21]}>
                <meshStandardMaterial color={exterior?.frames.color || '#4a3728'} />
            </mesh>
            <mesh geometry={nodes.Frame_DW_channel_1B.geometry} material={materials.Color_Exterior_channels} position={[-1.829, 0.336, 2.21]} />
            <mesh geometry={nodes.Frame_DW_W_1B.geometry} material={materials.Color_Exterior_Wood} position={[-1.829, 0.336, 2.21]} />
        </group>
    )
}

export function Model({ textures, exterior, ...props }: ModelProps) {
    const { nodes, materials } = useGLTF('/assets/models/1B.glb') as unknown as GLTFResult
    
    // Get opening types from config, defaulting to door for front and window for left
    const frontOpening = exterior?.openings?.front || 'door'
    const leftOpening = exterior?.openings?.left || 'window'
    
    return (
        <group {...props} dispose={null}>
            {/* Exterior Customization - Walls, Roof, Frames */}
            <ModelExterior nodes={nodes} materials={materials} textures={textures} exterior={exterior} />

            {/* Modular Openings - Front Slot */}
            <OpeningSlot
                slot="front"
                openingType={frontOpening}
                nodes={nodes}
                materials={materials}
                config={MODEL_1B_OPENINGS.front}
                frameColor={exterior?.frames.color}
            />

            {/* Modular Openings - Left Slot */}
            <OpeningSlot
                slot="left"
                openingType={leftOpening}
                nodes={nodes}
                materials={materials}
                config={MODEL_1B_OPENINGS.left}
                frameColor={exterior?.frames.color}
            />

            {/* Solar Panels Group - Preserved hierarchy */}
            <group position={[0, 2.112, 0]}>
                <group position={[0, 0, -1.247]}>
                    <mesh geometry={nodes.ConstSP_Left_1B.geometry} material={materials.Color_Dark} position={[-0.074, 0.025, 0.069]} rotation={[0.368, -Math.PI / 2, 0]} scale={0.025} />
                    <mesh geometry={nodes.Shield_Left_1B.geometry} material={materials.Color_Dark} position={[0, -0.384, -0.854]} rotation={[-0.012, 0, 0]} />
                    <group rotation={[-0.01, 0, 0]}>
                        <mesh geometry={nodes.SP_Left_1B_1.geometry} material={materials.Color_Solar} />
                        <mesh geometry={nodes.SP_Left_1B_2.geometry} material={materials.Solar_Panel} />
                    </group>
                </group>
                <group position={[0, 0, 1.247]}>
                    <mesh geometry={nodes.ConstSP_Right_1B.geometry} material={materials.Color_Dark} position={[-0.021, -0.046, -0.003]} rotation={[0.368, -Math.PI / 2, 0]} scale={0.025} />
                    <mesh geometry={nodes.Shield_Right_1B.geometry} material={materials.Color_Dark} position={[0, -0.393, 0.835]} rotation={[-0.012, 0, 0]} />
                    <group rotation={[-0.01, 0, 0]}>
                        <mesh geometry={nodes.SP_Right_1B_1.geometry} material={materials.Color_Solar} />
                        <mesh geometry={nodes.SP_Right_1B_2.geometry} material={materials.Solar_Panel} />
                    </group>
                </group>
                <mesh geometry={nodes.ElectricalPanel_Conduit_1B.geometry} material={materials.Color_Exterior} position={[-5.622, -3.7, 2.269]} rotation={[0, -1.571, 0]} scale={0.905} />
            </group>

            {/* Tesla Powerwall Group - Preserved hierarchy */}
            <group position={[0.694, -0.534, 2.378]} scale={0.365}>
                <group position={[-1.901, 1.464, -6.52]} scale={2.742}>
                    <mesh geometry={nodes.Tesla_powerwall_1.geometry} material={materials.Tesla} />
                    <mesh geometry={nodes.Tesla_powerwall_2.geometry} material={materials.Tesla_box} />
                </group>
                <group position={[-1.901, 1.464, -6.52]} scale={2.742}>
                    <mesh geometry={nodes.Tesla_shadow_1.geometry} material={materials.Tesla_wall} />
                    <mesh geometry={nodes.Tesla_shadow_2.geometry} material={materials.Tesla_floor} />
                </group>
            </group>

            {/* Other standalone elements */}
            <mesh geometry={nodes.Awning_DoorEnt_Front_1B.geometry} material={materials.Color_Exterior} position={[-1.831, 1.294, -2.261]} scale={0.025} />
            <mesh geometry={nodes.Black_Roof_1B.geometry} material={materials.Black} position={[0, 2.099, 0]} scale={0.025} />
            <mesh geometry={nodes.Bottom_1B.geometry} material={materials.Color_Dark} position={[0, -1.377, 0]} scale={0.025} />
            <mesh geometry={nodes.Deck_1B.geometry} material={materials.Cedar} />
            <mesh geometry={nodes.DoorEnt_1B.geometry} material={materials.Dark_Bronze} position={[-1.833, -0.143, -2.194]} rotation={[-Math.PI, 0, 0]} scale={-1} />
            <mesh geometry={nodes.ElectricalPanel1_Conduit_1B.geometry} material={materials.Color_Exterior} position={[-5.622, -1.589, 2.269]} rotation={[0, -1.571, 0]} scale={0.905} />
            <mesh geometry={nodes.Exhaust_1B.geometry} material={materials.Color_Exterior} position={[1.774, 0.692, 2.221]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.025} />
            
            {/* Interior and other non-exterior elements */}
            <mesh geometry={nodes.Glass_1B.geometry} material={materials.glassClear} position={[2.133, -0.185, -2.269]} scale={0.025} />
            <mesh geometry={nodes.GlassDoor_1B.geometry} material={materials.glassDoor} position={[-1.833, -0.143, -2.194]} rotation={[-Math.PI, 0, 0]} scale={-1} />
            <mesh geometry={nodes.Piles_1B.geometry} material={materials.Color_Piles} position={[0, -1.654, 0]} scale={0.025} />
            <mesh geometry={nodes.Spigot_1B.geometry} material={materials.Bronze} position={[-0.281, -0.624, 2.26]} rotation={[0, 1.571, 0]} scale={1.594} />
            <mesh geometry={nodes.Undersructure_1B.geometry} material={materials.Color_ExteriorSupp} position={[-1.829, -1.526, -3.079]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.Window_1B.geometry} material={materials.Dark_Bronze} position={[1.519, 0, 0]} scale={0.025} />
        </group>
    )
}

useGLTF.preload('/assets/models/1B.glb')
